services:

  # Launch just one coordinator node, not yet HA
  coordinator:
    build:
      context: .
      dockerfile: ./deploy/docker/coordinator.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - dfs-network

  datanode:
    build:
      context: .
      dockerfile: ./deploy/docker/datanode.Dockerfile
    ports:
      - "8081:8081"
    environment:
      - COORDINATOR_HOST=coordinator
      - COORDINATOR_PORT=8080
    depends_on:
      - coordinator
    networks:
      - dfs-network

  # Test runner service - runs integration tests against the cluster
  integration-runner:
    build:
      context: .
      dockerfile: ./deploy/docker/integration.Dockerfile
    environment:
      - TEST_FILES_DIR=/app/test-files
      - COORDINATOR_HOST=coordinator
      - COORDINATOR_PORT=8080
    depends_on:
      - coordinator
      - datanode
    networks:
      - dfs-network

networks:
  dfs-network:
    driver: bridge