name: Integration Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  integration:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: ./dfs

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./dfs/go.mod
          cache: true

      # Build and run the test environment and execute integration tests
      - name: Build and run integration tests with Docker Compose
        run: |
          docker compose -f docker-compose.test.yml up --build --exit-code-from integration-runner

      # Tear down the environment regardless of test result
      - name: Shutdown environment
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down --volumes --remove-orphans 