// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: datanode.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataNodeService_PrepareChunkUpload_FullMethodName   = "/dfs.DataNodeService/PrepareChunkUpload"
	DataNodeService_PrepareChunkDownload_FullMethodName = "/dfs.DataNodeService/PrepareChunkDownload"
	DataNodeService_UploadChunkStream_FullMethodName    = "/dfs.DataNodeService/UploadChunkStream"
	DataNodeService_DownloadChunkStream_FullMethodName  = "/dfs.DataNodeService/DownloadChunkStream"
	DataNodeService_DeleteChunk_FullMethodName          = "/dfs.DataNodeService/DeleteChunk"
	DataNodeService_BulkDeleteChunk_FullMethodName      = "/dfs.DataNodeService/BulkDeleteChunk"
	DataNodeService_HealthCheck_FullMethodName          = "/dfs.DataNodeService/HealthCheck"
)

// DataNodeServiceClient is the client API for DataNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataNodeServiceClient interface {
	// Hand-shake definitions from peer (upload and download, client or other DataNode)
	// Both operations follow a 2 step protocol: prepare -> stream data
	PrepareChunkUpload(ctx context.Context, in *UploadChunkRequest, opts ...grpc.CallOption) (*NodeReady, error)
	PrepareChunkDownload(ctx context.Context, in *DownloadChunkRequest, opts ...grpc.CallOption) (*DownloadReady, error)
	// Bidirectional stream for uploading chunk data to a node.
	// The client streams data, the server streams back acknowledgements.
	UploadChunkStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChunkDataStream, ChunkDataAck], error)
	// Server-side stream for downloading chunk data from a node.
	// The client sends a single request, the server streams back data.
	DownloadChunkStream(ctx context.Context, in *DownloadStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChunkDataStream], error)
	// Unary operation to delete a chunk
	DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error)
	BulkDeleteChunk(ctx context.Context, in *BulkDeleteChunkRequest, opts ...grpc.CallOption) (*BulkDeleteChunkResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type dataNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataNodeServiceClient(cc grpc.ClientConnInterface) DataNodeServiceClient {
	return &dataNodeServiceClient{cc}
}

func (c *dataNodeServiceClient) PrepareChunkUpload(ctx context.Context, in *UploadChunkRequest, opts ...grpc.CallOption) (*NodeReady, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeReady)
	err := c.cc.Invoke(ctx, DataNodeService_PrepareChunkUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeServiceClient) PrepareChunkDownload(ctx context.Context, in *DownloadChunkRequest, opts ...grpc.CallOption) (*DownloadReady, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadReady)
	err := c.cc.Invoke(ctx, DataNodeService_PrepareChunkDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeServiceClient) UploadChunkStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChunkDataStream, ChunkDataAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataNodeService_ServiceDesc.Streams[0], DataNodeService_UploadChunkStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChunkDataStream, ChunkDataAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataNodeService_UploadChunkStreamClient = grpc.BidiStreamingClient[ChunkDataStream, ChunkDataAck]

func (c *dataNodeServiceClient) DownloadChunkStream(ctx context.Context, in *DownloadStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChunkDataStream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataNodeService_ServiceDesc.Streams[1], DataNodeService_DownloadChunkStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadStreamRequest, ChunkDataStream]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataNodeService_DownloadChunkStreamClient = grpc.ServerStreamingClient[ChunkDataStream]

func (c *dataNodeServiceClient) DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChunkResponse)
	err := c.cc.Invoke(ctx, DataNodeService_DeleteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeServiceClient) BulkDeleteChunk(ctx context.Context, in *BulkDeleteChunkRequest, opts ...grpc.CallOption) (*BulkDeleteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkDeleteChunkResponse)
	err := c.cc.Invoke(ctx, DataNodeService_BulkDeleteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, DataNodeService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataNodeServiceServer is the server API for DataNodeService service.
// All implementations must embed UnimplementedDataNodeServiceServer
// for forward compatibility.
type DataNodeServiceServer interface {
	// Hand-shake definitions from peer (upload and download, client or other DataNode)
	// Both operations follow a 2 step protocol: prepare -> stream data
	PrepareChunkUpload(context.Context, *UploadChunkRequest) (*NodeReady, error)
	PrepareChunkDownload(context.Context, *DownloadChunkRequest) (*DownloadReady, error)
	// Bidirectional stream for uploading chunk data to a node.
	// The client streams data, the server streams back acknowledgements.
	UploadChunkStream(grpc.BidiStreamingServer[ChunkDataStream, ChunkDataAck]) error
	// Server-side stream for downloading chunk data from a node.
	// The client sends a single request, the server streams back data.
	DownloadChunkStream(*DownloadStreamRequest, grpc.ServerStreamingServer[ChunkDataStream]) error
	// Unary operation to delete a chunk
	DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error)
	BulkDeleteChunk(context.Context, *BulkDeleteChunkRequest) (*BulkDeleteChunkResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedDataNodeServiceServer()
}

// UnimplementedDataNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataNodeServiceServer struct{}

func (UnimplementedDataNodeServiceServer) PrepareChunkUpload(context.Context, *UploadChunkRequest) (*NodeReady, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareChunkUpload not implemented")
}
func (UnimplementedDataNodeServiceServer) PrepareChunkDownload(context.Context, *DownloadChunkRequest) (*DownloadReady, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareChunkDownload not implemented")
}
func (UnimplementedDataNodeServiceServer) UploadChunkStream(grpc.BidiStreamingServer[ChunkDataStream, ChunkDataAck]) error {
	return status.Errorf(codes.Unimplemented, "method UploadChunkStream not implemented")
}
func (UnimplementedDataNodeServiceServer) DownloadChunkStream(*DownloadStreamRequest, grpc.ServerStreamingServer[ChunkDataStream]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadChunkStream not implemented")
}
func (UnimplementedDataNodeServiceServer) DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChunk not implemented")
}
func (UnimplementedDataNodeServiceServer) BulkDeleteChunk(context.Context, *BulkDeleteChunkRequest) (*BulkDeleteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkDeleteChunk not implemented")
}
func (UnimplementedDataNodeServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDataNodeServiceServer) mustEmbedUnimplementedDataNodeServiceServer() {}
func (UnimplementedDataNodeServiceServer) testEmbeddedByValue()                         {}

// UnsafeDataNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataNodeServiceServer will
// result in compilation errors.
type UnsafeDataNodeServiceServer interface {
	mustEmbedUnimplementedDataNodeServiceServer()
}

func RegisterDataNodeServiceServer(s grpc.ServiceRegistrar, srv DataNodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataNodeService_ServiceDesc, srv)
}

func _DataNodeService_PrepareChunkUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServiceServer).PrepareChunkUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeService_PrepareChunkUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServiceServer).PrepareChunkUpload(ctx, req.(*UploadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNodeService_PrepareChunkDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServiceServer).PrepareChunkDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeService_PrepareChunkDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServiceServer).PrepareChunkDownload(ctx, req.(*DownloadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNodeService_UploadChunkStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataNodeServiceServer).UploadChunkStream(&grpc.GenericServerStream[ChunkDataStream, ChunkDataAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataNodeService_UploadChunkStreamServer = grpc.BidiStreamingServer[ChunkDataStream, ChunkDataAck]

func _DataNodeService_DownloadChunkStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataNodeServiceServer).DownloadChunkStream(m, &grpc.GenericServerStream[DownloadStreamRequest, ChunkDataStream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataNodeService_DownloadChunkStreamServer = grpc.ServerStreamingServer[ChunkDataStream]

func _DataNodeService_DeleteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServiceServer).DeleteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeService_DeleteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServiceServer).DeleteChunk(ctx, req.(*DeleteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNodeService_BulkDeleteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkDeleteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServiceServer).BulkDeleteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeService_BulkDeleteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServiceServer).BulkDeleteChunk(ctx, req.(*BulkDeleteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNodeService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataNodeService_ServiceDesc is the grpc.ServiceDesc for DataNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfs.DataNodeService",
	HandlerType: (*DataNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareChunkUpload",
			Handler:    _DataNodeService_PrepareChunkUpload_Handler,
		},
		{
			MethodName: "PrepareChunkDownload",
			Handler:    _DataNodeService_PrepareChunkDownload_Handler,
		},
		{
			MethodName: "DeleteChunk",
			Handler:    _DataNodeService_DeleteChunk_Handler,
		},
		{
			MethodName: "BulkDeleteChunk",
			Handler:    _DataNodeService_BulkDeleteChunk_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DataNodeService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadChunkStream",
			Handler:       _DataNodeService_UploadChunkStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadChunkStream",
			Handler:       _DataNodeService_DownloadChunkStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "datanode.proto",
}
