name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'dfs/go.mod'

    - name: Install dependencies
      working-directory: ./dfs
      run: go mod download

    - name: Build all components
      working-directory: ./dfs
      run: |
        go build ./cmd/coordinator
        go build ./cmd/datanode  
        go build ./cmd/client