name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dfs

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Check Go version
      run: go version

    - name: Install dependencies
      run: |
        go mod download
        go mod verify
        go mod tidy

    - name: Build
      run: |
        echo "Building packages..."
        go build -v ./...
        echo "Build completed"

    - name: Test
      run: |
        echo "Running tests..."
        go test -v -race ./...
        echo "Tests completed"